use serde::{Deserialize, Deserializer, Serialize};

macro_rules! id {
    ($name:ident) => {
        #[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize)]
        #[serde(transparent)]
        pub struct $name(String);
        impl $name {
            pub fn parse(value: impl Into<String>) -> Result<Self, &'static str> {
                let value = value.into();
                if value.is_empty()
                    || value.len() > 128
                    || value.bytes().any(|b| !b.is_ascii_graphic())
                {
                    return Err("invalid opaque id");
                }
                Ok(Self(value))
            }
            pub fn new(value: impl Into<String>) -> Self {
                Self::parse(value).expect("valid opaque id")
            }
            pub fn as_str(&self) -> &str {
                &self.0
            }
        }
        impl<'de> Deserialize<'de> for $name {
            fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
                let value = String::deserialize(deserializer)?;
                Self::parse(value).map_err(serde::de::Error::custom)
            }
        }
    };
}
id!(SeatId);
id!(ThreadId);
/// Server message IDs exclude the private `local:` recovery-token namespace.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize)]
#[serde(transparent)]
pub struct MessageId(String);
impl MessageId {
    pub fn parse(value: impl Into<String>) -> Result<Self, &'static str> {
        let value = value.into();
        if value.is_empty()
            || value.len() > 128
            || value.starts_with("local:")
            || value.bytes().any(|b| !b.is_ascii_graphic())
        {
            return Err("invalid message id");
        }
        Ok(Self(value))
    }
    pub fn new(value: impl Into<String>) -> Self {
        Self::parse(value).expect("valid message id")
    }
    pub fn as_str(&self) -> &str {
        &self.0
    }
}
impl<'de> Deserialize<'de> for MessageId {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Self::parse(value).map_err(serde::de::Error::custom)
    }
}
id!(InvitationId);
id!(RequirementId);
id!(ServiceAuthorId);
id!(OperationId);
id!(RetirementJobId);
id!(HostTargetId);
id!(TerminalId);
id!(HostCallId);
id!(HostBootId);
id!(NativeSessionId);
id!(ExecutionId);
id!(WakeAttemptId);

/// Private journal lookup token; it never names a server receipt or message.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize)]
#[serde(transparent)]
pub struct LocalRecoveryRef(String);
impl LocalRecoveryRef {
    pub fn parse(value: impl Into<String>) -> Result<Self, &'static str> {
        let value = value.into();
        if !value.starts_with("local:")
            || value.len() <= "local:".len()
            || value.len() > 64
            || value.bytes().any(|b| !b.is_ascii_graphic())
        {
            return Err("invalid local recovery reference");
        }
        Ok(Self(value))
    }
    pub fn as_str(&self) -> &str {
        &self.0
    }
}
impl<'de> Deserialize<'de> for LocalRecoveryRef {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Self::parse(value).map_err(serde::de::Error::custom)
    }
}

/// Public ID prefixes. A public ID is `<prefix>-<suffix>`; new IDs carry a
/// short base62 suffix (see [`generate_public_id`]), while IDs stored before
/// the short form keep their UUID suffix. Every validator treats IDs as
/// opaque, so both forms are accepted everywhere.
pub mod prefix {
    pub const SEAT: &str = "seat";
    pub const THREAD: &str = "thread";
    pub const INVITATION: &str = "inv";
    pub const REQUIREMENT: &str = "requirement";
    pub const RETIREMENT: &str = "retirement";
    pub const EVENT: &str = "event";
    /// Send preparation; its ordinary message is `msg-<same suffix>`.
    pub const SEND_PREPARATION: &str = "prep";
    pub const MESSAGE: &str = "msg";
    /// Service notification preparation; its message is `notify-<same suffix>`.
    pub const NOTIFY_PREPARATION: &str = "notify-prep";
    pub const NOTIFY: &str = "notify";
}

/// Length of the random base62 suffix of a newly generated public ID:
/// 62^8 ≈ 2^47.6 values, ample for one local machine's store. Collisions are
/// still detected and regenerated by the store (`store::public_ids`).
pub const PUBLIC_ID_SUFFIX_LEN: usize = 8;

const BASE62: &[u8; 62] = b"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";

/// A fresh random base62 suffix of [`PUBLIC_ID_SUFFIX_LEN`] characters.
///
/// The entropy comes from the OS CSPRNG (via `uuid::Uuid::new_v4`): the 104
/// fully random bits of a v4 UUID (its version and variant bytes skipped) are
/// reduced modulo 62^8, so the bias is below 2^-56.
pub fn public_id_suffix() -> String {
    let bytes = uuid::Uuid::new_v4().into_bytes();
    let mut random: u128 = 0;
    for (index, byte) in bytes.iter().enumerate() {
        // Byte 6 holds the version nibble, byte 8 the variant bits.
        if index != 6 && index != 8 {
            random = (random << 8) | u128::from(*byte);
        }
    }
    let mut suffix = [0u8; PUBLIC_ID_SUFFIX_LEN];
    for slot in &mut suffix {
        *slot = BASE62[(random % 62) as usize];
        random /= 62;
    }
    String::from_utf8(suffix.to_vec()).expect("base62 is ASCII")
}

/// A fresh public ID `<prefix>-<8 base62 chars>`, e.g. `seat-k3Fq9a2B`.
/// Callers that persist it must go through `store::public_ids`, which
/// regenerates on collision.
pub fn generate_public_id(prefix: &str) -> String {
    format!("{prefix}-{}", public_id_suffix())
}

/// True when `value` is `<prefix>-<8 base62 chars>` (the short form).
pub fn is_short_public_id(prefix: &str, value: &str) -> bool {
    value
        .strip_prefix(prefix)
        .and_then(|rest| rest.strip_prefix('-'))
        .is_some_and(|suffix| {
            suffix.len() == PUBLIC_ID_SUFFIX_LEN
                && suffix.bytes().all(|b| b.is_ascii_alphanumeric())
        })
}

#[cfg(test)]
mod public_id_tests {
    use super::*;

    #[test]
    fn generated_ids_are_prefix_and_eight_base62_chars() {
        for prefix in [
            prefix::SEAT,
            prefix::THREAD,
            prefix::INVITATION,
            prefix::EVENT,
        ] {
            let id = generate_public_id(prefix);
            assert!(is_short_public_id(prefix, &id), "{id}");
            assert_eq!(id.len(), prefix.len() + 1 + PUBLIC_ID_SUFFIX_LEN);
            SeatId::parse(id.clone()).unwrap();
            MessageId::parse(id).unwrap();
        }
    }

    #[test]
    fn generated_suffixes_are_distinct_and_span_the_alphabet() {
        let mut seen = std::collections::HashSet::new();
        let mut alphabet = std::collections::HashSet::new();
        for _ in 0..4096 {
            let suffix = public_id_suffix();
            alphabet.extend(suffix.bytes());
            assert!(seen.insert(suffix), "suffix repeated within 4096 draws");
        }
        assert_eq!(alphabet.len(), 62, "every base62 digit should appear");
    }

    #[test]
    fn legacy_uuid_ids_remain_valid() {
        let legacy = "seat-bc121d12-9d30-4510-b93c-e7cd26e890f1";
        assert_eq!(SeatId::parse(legacy).unwrap().as_str(), legacy);
        ThreadId::parse("thread-bc121d12-9d30-4510-b93c-e7cd26e890f1").unwrap();
        InvitationId::parse("invitation-bc121d12-9d30-4510-b93c-e7cd26e890f1").unwrap();
        MessageId::parse("msg-bc121d12-9d30-4510-b93c-e7cd26e890f1").unwrap();
        assert!(!is_short_public_id(prefix::SEAT, legacy));
        assert!(!is_short_public_id(prefix::SEAT, "seat-k3Fq9a2"));
        assert!(!is_short_public_id(prefix::SEAT, "seat-k3Fq9a2_"));
        assert!(is_short_public_id(prefix::SEAT, "seat-k3Fq9a2B"));
    }
}
